import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const monse = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tricel - Votaciones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${monse.className} min-w-min`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
